name: xfocus_mobile
description: xfocus mobile.

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7
  archive: ^2.0.4
  async_loader: ^0.1.2
  bloc: ^0.7.7
  cached_network_image: ^0.5.1
  camera: ^0.2.6
  card_settings: ^1.2.2
  carousel_pro: ^0.0.13
  charts_flutter: ^0.5.0
  chewie: ^0.8.0
  date_range_picker: ^1.0.1
  device_info: ^0.3.0
  dio: ^1.0.13
  firebase_admob: 0.6.1
  firebase_analytics: ^1.0.6
  firebase_auth: ^0.6.6
  firebase_messaging: ^2.1.0
  fluro: ^1.4.0
  flutter_app_badger: ^1.0.2
  flutter_cache_manager: ^0.2.0+1
  flutter_calendar_carousel: ^1.3.5
  flutter_circular_chart: ^0.1.0
  flutter_full_pdf_viewer: ^1.0.1
  flutter_local_notifications: 0.4.2+1
  flutter_markdown: ^0.2.0
  flutter_picker: ^1.0.5
  flutter_range_slider: ^1.0.1
  flutter_redux: ^0.5.2
  flutter_search_bar: ^2.0.7
  flutter_sequence_animation: ^3.0.1
  flutter_slidable: ^0.4.9
  flutter_socket_io: ^0.4.5
  flutter_sparkline: ^0.1.0
  flutter_speed_dial: ^1.0.9
  flutter_spinkit: ^3.1.0
  flutter_staggered_grid_view: ^0.2.5
  flutter_statusbar_manager: ^1.0.2
  flutter_svg: ^0.8.2
  flutter_swiper: ^1.1.4
  font_awesome_flutter: ^8.2.0
  google_sign_in: ^3.2.4
  http: ^0.12.0
  image_picker: ^0.4.10
  intl: ^0.15.7
  intro_views_flutter: ^2.4.0
  json_annotation: ^1.2.0
  json_serializable: ^1.5.1
  material_design_icons_flutter: ^3.0.3289
  material_search: ^0.2.8
  meta: ^1.1.6
  onesignal: ^1.0.3
  open_file: ^1.1.1
  open_iconic_flutter: ^0.3.0
  path_provider: ^0.4.1
  pdf: ^1.0.8
  percent_indicator: ^1.0.11
  qr_flutter: ^1.1.5
  qr_reader: ^0.1.3
  quick_actions: ^0.2.2
  redux: ^3.0.0
  rxdart: ^0.20.0
  shared_preferences: ^0.4.3
  simple_auth_flutter: ^2.0.0
  sqflite: any
  sticky_headers: ^0.1.7
  video_player: ^0.7.0
  web_socket_channel: ^1.0.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/json/cash.json
    - assets/json/inventory.json
    - assets/json/account_receivable.json
    - assets/json/account_payable.json
    - assets/json/sales.json
    - assets/json/counter.json
    - assets/png/logo.png
    - assets/png/logo-50.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
